
import instagramproject.CurrentProfile;
import instagramproject.RealProfile;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Graphics2D;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.border.Border;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jose
 */
public class ProfilePopUp extends javax.swing.JFrame {

    private boolean follow;
    private static ImageIcon ii;
    int width = (Toolkit.getDefaultToolkit().getScreenSize().width / 2) - 262;
    int height = (Toolkit.getDefaultToolkit().getScreenSize().height / 2) - 250;
    /**
     * Creates new form ProfilePopUp
     */
    public ProfilePopUp(Icon i, String username, String firstname,
            String lastname, int followers, int following, boolean follow, RealProfile loggedIn) {
        initComponents();
        this.setTitle("EagleGram");
        this.setLocation(width, height);
        
        profilePictureLabel.setIcon(i);
        usernameLabel.setText(username);
        firstNameLabel.setText(firstname);
        lastNameLabel.setText(lastname);
        followersLabel.setText(Integer.toString(followers)+" followers");
        followingLabel.setText(Integer.toString(following)+" following");
        if (follow)
            followButton.setText("unFollow");
        
        this.findProfile(username);
        /*
        for(number of post)
        profilePostsPanel.add(new UserPanel(picturePath, caption, time, likes));
        profilePostsPanel.revalidate();
        profilePostsPanel.repaint();
        */
        for(int j = 0; j < current.getPosts().size(); j++) {
            profilePostsPanel.add(new UserPanel(current.getPosts().get(j).getImage(), current.getPosts().get(j).getCaption(), current.getPosts().get(j).getDate(), current.getPosts().get(j).getLikes()));
            profilePostsPanel.revalidate();
            profilePostsPanel.repaint();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        staticProfilePanel = new javax.swing.JPanel();
        profilePictureLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        followersLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        followingLabel = new javax.swing.JLabel();
        followButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        profilePostsPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        staticProfilePanel.setPreferredSize(new java.awt.Dimension(536, 88));

        profilePictureLabel.setPreferredSize(new java.awt.Dimension(77, 77));
        try {
            ii=new ImageIcon(scaleImage(77, 77, ImageIO.read(new File(System.getProperty("user.dir")+"\\ProfilePicture.png"))));//get the image from file chooser and scale it to match JLabel size
            profilePictureLabel.setIcon(ii);
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        usernameLabel.setText("Username");
        usernameLabel.setPreferredSize(new java.awt.Dimension(100, 21));

        firstNameLabel.setText("First name");
        firstNameLabel.setPreferredSize(new java.awt.Dimension(100, 21));

        followersLabel.setText("# followers");
        followersLabel.setPreferredSize(new java.awt.Dimension(100, 21));

        lastNameLabel.setText("Last name");
        lastNameLabel.setPreferredSize(new java.awt.Dimension(100, 21));

        followingLabel.setText("# following");
        followingLabel.setPreferredSize(new java.awt.Dimension(100, 21));

        followButton.setText("Follow");
        followButton.setPreferredSize(new java.awt.Dimension(100, 21));
        followButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                followButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout staticProfilePanelLayout = new javax.swing.GroupLayout(staticProfilePanel);
        staticProfilePanel.setLayout(staticProfilePanelLayout);
        staticProfilePanelLayout.setHorizontalGroup(
            staticProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staticProfilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profilePictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(staticProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(staticProfilePanelLayout.createSequentialGroup()
                        .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(followersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(followingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(followButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(staticProfilePanelLayout.createSequentialGroup()
                        .addComponent(firstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        staticProfilePanelLayout.setVerticalGroup(
            staticProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, staticProfilePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(staticProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(staticProfilePanelLayout.createSequentialGroup()
                        .addGroup(staticProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(followersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(followingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(followButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(staticProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(profilePictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jScrollPane1.setPreferredSize(new java.awt.Dimension(534, 404));

        profilePostsPanel.setMinimumSize(new java.awt.Dimension(534, 404));

        javax.swing.GroupLayout profilePostsPanelLayout = new javax.swing.GroupLayout(profilePostsPanel);
        profilePostsPanel.setLayout(profilePostsPanelLayout);
        profilePostsPanelLayout.setHorizontalGroup(
            profilePostsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 534, Short.MAX_VALUE)
        );
        profilePostsPanelLayout.setVerticalGroup(
            profilePostsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(profilePostsPanel);
        profilePostsPanel.setLayout(new BoxLayout(profilePostsPanel, BoxLayout.Y_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(staticProfilePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(staticProfilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void findProfile(String username){
        for(int i = 0; i < main.getAllProfiles().size(); i++){
            if(main.getAllProfiles().get(i).getUsername().equals(username)){
                current = main.getAllProfiles().get(i);
            }        
        }
    }
    
    private void followButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_followButtonActionPerformed
        // TODO add your handling code here:
        if (follow == false){
            //add users togeather
            follow=true;
            main.getLoggedIn().addFollowing(current);
            main.following(current.getUsername(), main.getLoggedIn().getUsername());
            followButton.setText("unFollow");
        }
        else
        {
            //do stuff
            follow=false;
            main.getLoggedIn().removeFollowing(current);
            main.removeFollowing(current.getUsername(), main.getLoggedIn().getUsername());
            followButton.setText("Follow");
        }
    }//GEN-LAST:event_followButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfilePopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfilePopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfilePopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfilePopUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ProfilePopUp(null, "username", "firstname",
                        "lastname",0,0,false, null).setVisible(true);
            }
        });
    }
    
    public static BufferedImage scaleImage(int w, int h, BufferedImage img) throws Exception {
        BufferedImage bi;
        bi = new BufferedImage(w, h, BufferedImage.TRANSLUCENT);
        Graphics2D g2d = (Graphics2D) bi.createGraphics();
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2d.addRenderingHints(new RenderingHints(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY));
        g2d.drawImage(img, 0, 0, w, h, null);
        g2d.dispose();
        return bi;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JButton followButton;
    private javax.swing.JLabel followersLabel;
    private javax.swing.JLabel followingLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JLabel profilePictureLabel;
    private javax.swing.JPanel profilePostsPanel;
    private javax.swing.JPanel staticProfilePanel;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
    private CurrentProfile main = new CurrentProfile();
    private RealProfile current;
    
    private class UserPanel extends JPanel {

        public UserPanel(Icon ii, String caption, String date, int likes) {
            setLayout(new GridBagLayout());
            Border emptyBorder = BorderFactory.createEmptyBorder(2, 2, 2, 2);
            Border lineBorder = BorderFactory.createLineBorder(Color.black);
            setBorder(BorderFactory.createCompoundBorder(lineBorder, emptyBorder));

            JLabel timeLabel = new JLabel();
            timeLabel.setSize(100, 21);
            timeLabel.setText(date);
            add(timeLabel, createGbc(3, 0));

            JLabel pictureLabel = new JLabel();
            pictureLabel.setSize(120, 120);
            try {
                pictureLabel.setIcon(ii);
            } catch (Exception ex) {
                ex.printStackTrace();
            }
            pictureLabel.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            pictureLabel.addMouseListener(new MouseAdapter()  {  
                public void mouseClicked(MouseEvent e)  
                {  
                    //PostPopUp frame= new PostPopUp(ii, username, likes, liked,
                      //      caption, "comments", "hashtags","people");
                    
                    //frame.setVisible(true);
                    
                    
                }  
            });
            add(pictureLabel, createGbc(0, 0));

            JTextArea captionText = new JTextArea();
            captionText.setText(caption);
            captionText.setLineWrap(true);
            captionText.setEditable(false);
            captionText.setSize(120, 120);
            JScrollPane CaptionScroll = new JScrollPane(captionText,
                    JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED,
                    JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
            CaptionScroll.setSize(120, 120);
            add(captionText, createGbc(1, 0));

            final JLabel likeLabel = new JLabel();
            likeLabel.setText("LIKES: " + Integer.toString(likes));
            likeLabel.setSize(100, 21);
            add(likeLabel, createGbc(2,0));
        }

        private GridBagConstraints createGbc(int x, int y) {
            GridBagConstraints gbc = new GridBagConstraints();
            gbc.gridx = x;
            gbc.gridy = y;
            gbc.gridwidth = 1;
            gbc.gridheight = 1;
            gbc.weightx = 1.0;
            gbc.weighty = 1.0;
            gbc.anchor = GridBagConstraints.WEST;

            return gbc;
        }
    }
}
